INSERT INTO PUBLIC.SUBDIVISION (ID, CODE, PARENT_ID) VALUES (1, 's1', null);
INSERT INTO PUBLIC.SUBDIVISION (ID, CODE, PARENT_ID) VALUES (2, 's2', 1);
INSERT INTO PUBLIC.SUBDIVISION (ID, CODE, PARENT_ID) VALUES (3, 's3', 1);
INSERT INTO PUBLIC.SUBDIVISION (ID, CODE, PARENT_ID) VALUES (4, 's4', 2);
INSERT INTO PUBLIC.SUBDIVISION (ID, CODE, PARENT_ID) VALUES (5, 's5', 4);

INSERT INTO PUBLIC.EMPLOYEE (ID, FIRST_NAME, LAST_NAME, NUMBER, SUBDIVISION_ID) VALUES (1, 'John', 'Walsh', '16421', 2);
INSERT INTO PUBLIC.EMPLOYEE (ID, FIRST_NAME, LAST_NAME, NUMBER, SUBDIVISION_ID) VALUES (2, 'Mike', 'Smith', '12366', 3);
INSERT INTO PUBLIC.EMPLOYEE (ID, FIRST_NAME, LAST_NAME, NUMBER, SUBDIVISION_ID) VALUES (3, 'Mike', 'Smith', '643232', 4);
INSERT INTO PUBLIC.EMPLOYEE (ID, FIRST_NAME, LAST_NAME, NUMBER, SUBDIVISION_ID) VALUES (4, 'Nick', 'Groter', '112356', 5);
INSERT INTO PUBLIC.EMPLOYEE (ID, FIRST_NAME, LAST_NAME, NUMBER, SUBDIVISION_ID) VALUES (5, 'Rom', 'Mack', '63242', 2);
INSERT INTO PUBLIC.EMPLOYEE (ID, FIRST_NAME, LAST_NAME, NUMBER, SUBDIVISION_ID) VALUES (6, 'Maria', 'Dolli', 'I-432', 5);
INSERT INTO PUBLIC.EMPLOYEE (ID, FIRST_NAME, LAST_NAME, NUMBER, SUBDIVISION_ID) VALUES (7, 'Selli', 'Dodster', 'F-321', 5);
INSERT INTO PUBLIC.EMPLOYEE (ID, FIRST_NAME, LAST_NAME, NUMBER, SUBDIVISION_ID) VALUES (8, 'Kriek', 'Jet', 'U-01', 5);
INSERT INTO PUBLIC.EMPLOYEE (ID, FIRST_NAME, LAST_NAME, NUMBER, SUBDIVISION_ID) VALUES (9, 'Rebeca', 'Orange', '431', 5);
INSERT INTO PUBLIC.EMPLOYEE (ID, FIRST_NAME, LAST_NAME, NUMBER, SUBDIVISION_ID) VALUES (10, 'Sam', 'Nil', 'ROW-123', 5);
INSERT INTO PUBLIC.EMPLOYEE (ID, FIRST_NAME, LAST_NAME, NUMBER, SUBDIVISION_ID) VALUES (11, 'Gera', 'Argo', '32234', 5);
